# Generated by Django 2.2.7 on 2019-11-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='packId',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
