# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcards', '0004_auto_20191126_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='packId',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
